// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cs.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ERROR_CODE int32

const (
	ERROR_CODE_SUCCESS ERROR_CODE = 0
	ERROR_CODE_FAILED  ERROR_CODE = 1
)

// Enum value maps for ERROR_CODE.
var (
	ERROR_CODE_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	ERROR_CODE_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x ERROR_CODE) Enum() *ERROR_CODE {
	p := new(ERROR_CODE)
	*p = x
	return p
}

func (x ERROR_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERROR_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[0].Descriptor()
}

func (ERROR_CODE) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[0]
}

func (x ERROR_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERROR_CODE.Descriptor instead.
func (ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type CSMsgID int32

const (
	CSMsgID_REQ_BEGIN              CSMsgID = 0
	CSMsgID_REQ_LOGIN              CSMsgID = 1
	CSMsgID_REQ_HEARTBEAT          CSMsgID = 2
	CSMsgID_REQ_SET_USERNAME       CSMsgID = 3
	CSMsgID_REQ_ROOM_CHAT          CSMsgID = 4
	CSMsgID_REQ_ROOM_LIST          CSMsgID = 5
	CSMsgID_REQ_JOIN_ROOM          CSMsgID = 6
	CSMsgID_RSP_BEGIN              CSMsgID = 100
	CSMsgID_RSP_LOGIN              CSMsgID = 101
	CSMsgID_RSP_HEARTBEAT          CSMsgID = 102
	CSMsgID_RSP_SET_USERNAME       CSMsgID = 103
	CSMsgID_RSP_ROOM_CHAT          CSMsgID = 104
	CSMsgID_RSP_ROOM_LIST          CSMsgID = 105
	CSMsgID_RSP_JOIN_ROOM          CSMsgID = 106
	CSMsgID_NTF_BEGIN              CSMsgID = 200
	CSMsgID_NTF_ROOM_MEMBER_ONLINE CSMsgID = 201
	CSMsgID_NTF_ROOM_CHAT          CSMsgID = 202
	CSMsgID_NTF_ROOM_CLOSED        CSMsgID = 203
	CSMsgID_NTF_HISTROY_MSG        CSMsgID = 204
)

// Enum value maps for CSMsgID.
var (
	CSMsgID_name = map[int32]string{
		0:   "REQ_BEGIN",
		1:   "REQ_LOGIN",
		2:   "REQ_HEARTBEAT",
		3:   "REQ_SET_USERNAME",
		4:   "REQ_ROOM_CHAT",
		5:   "REQ_ROOM_LIST",
		6:   "REQ_JOIN_ROOM",
		100: "RSP_BEGIN",
		101: "RSP_LOGIN",
		102: "RSP_HEARTBEAT",
		103: "RSP_SET_USERNAME",
		104: "RSP_ROOM_CHAT",
		105: "RSP_ROOM_LIST",
		106: "RSP_JOIN_ROOM",
		200: "NTF_BEGIN",
		201: "NTF_ROOM_MEMBER_ONLINE",
		202: "NTF_ROOM_CHAT",
		203: "NTF_ROOM_CLOSED",
		204: "NTF_HISTROY_MSG",
	}
	CSMsgID_value = map[string]int32{
		"REQ_BEGIN":              0,
		"REQ_LOGIN":              1,
		"REQ_HEARTBEAT":          2,
		"REQ_SET_USERNAME":       3,
		"REQ_ROOM_CHAT":          4,
		"REQ_ROOM_LIST":          5,
		"REQ_JOIN_ROOM":          6,
		"RSP_BEGIN":              100,
		"RSP_LOGIN":              101,
		"RSP_HEARTBEAT":          102,
		"RSP_SET_USERNAME":       103,
		"RSP_ROOM_CHAT":          104,
		"RSP_ROOM_LIST":          105,
		"RSP_JOIN_ROOM":          106,
		"NTF_BEGIN":              200,
		"NTF_ROOM_MEMBER_ONLINE": 201,
		"NTF_ROOM_CHAT":          202,
		"NTF_ROOM_CLOSED":        203,
		"NTF_HISTROY_MSG":        204,
	}
)

func (x CSMsgID) Enum() *CSMsgID {
	p := new(CSMsgID)
	*p = x
	return p
}

func (x CSMsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CSMsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[1].Descriptor()
}

func (CSMsgID) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[1]
}

func (x CSMsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CSMsgID.Descriptor instead.
func (CSMsgID) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

type CSHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID        CSMsgID `protobuf:"varint,1,opt,name=MsgID,proto3,enum=pb.CSMsgID" json:"MsgID,omitempty"`
	BodyLen      int32   `protobuf:"varint,2,opt,name=BodyLen,proto3" json:"BodyLen,omitempty"`
	IsCompressed bool    `protobuf:"varint,3,opt,name=IsCompressed,proto3" json:"IsCompressed,omitempty"`
}

func (x *CSHead) Reset() {
	*x = CSHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSHead) ProtoMessage() {}

func (x *CSHead) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSHead.ProtoReflect.Descriptor instead.
func (*CSHead) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

func (x *CSHead) GetMsgID() CSMsgID {
	if x != nil {
		return x.MsgID
	}
	return CSMsgID_REQ_BEGIN
}

func (x *CSHead) GetBodyLen() int32 {
	if x != nil {
		return x.BodyLen
	}
	return 0
}

func (x *CSHead) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

type CSReqBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq         int64             `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Login       *CSReqLogin       `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	Heartbeat   *CSReqHeartbeat   `protobuf:"bytes,3,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"`
	SetUsername *CSReqSetUsername `protobuf:"bytes,4,opt,name=SetUsername,proto3" json:"SetUsername,omitempty"`
	RoomChat    *CSReqRoomChat    `protobuf:"bytes,5,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomList    *CSReqRoomList    `protobuf:"bytes,6,opt,name=RoomList,proto3" json:"RoomList,omitempty"`
	JoinRoom    *CSReqJoinRoom    `protobuf:"bytes,7,opt,name=JoinRoom,proto3" json:"JoinRoom,omitempty"`
}

func (x *CSReqBody) Reset() {
	*x = CSReqBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqBody) ProtoMessage() {}

func (x *CSReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqBody.ProtoReflect.Descriptor instead.
func (*CSReqBody) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *CSReqBody) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CSReqBody) GetLogin() *CSReqLogin {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *CSReqBody) GetHeartbeat() *CSReqHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *CSReqBody) GetSetUsername() *CSReqSetUsername {
	if x != nil {
		return x.SetUsername
	}
	return nil
}

func (x *CSReqBody) GetRoomChat() *CSReqRoomChat {
	if x != nil {
		return x.RoomChat
	}
	return nil
}

func (x *CSReqBody) GetRoomList() *CSReqRoomList {
	if x != nil {
		return x.RoomList
	}
	return nil
}

func (x *CSReqBody) GetJoinRoom() *CSReqJoinRoom {
	if x != nil {
		return x.JoinRoom
	}
	return nil
}

type CSRspBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq         int64             `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	ErrCode     ERROR_CODE        `protobuf:"varint,2,opt,name=ErrCode,proto3,enum=pb.ERROR_CODE" json:"ErrCode,omitempty"`
	ErrMsg      string            `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Login       *CSRspLogin       `protobuf:"bytes,4,opt,name=Login,proto3" json:"Login,omitempty"`
	Heartbeat   *CSRspHeartbeat   `protobuf:"bytes,5,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"`
	SetUsername *CSRspSetUsername `protobuf:"bytes,6,opt,name=SetUsername,proto3" json:"SetUsername,omitempty"`
	RoomChat    *CSRspRoomChat    `protobuf:"bytes,7,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomList    *CSRspRoomList    `protobuf:"bytes,8,opt,name=RoomList,proto3" json:"RoomList,omitempty"`
	JoinRoom    *CSRspJoinRoom    `protobuf:"bytes,9,opt,name=JoinRoom,proto3" json:"JoinRoom,omitempty"`
}

func (x *CSRspBody) Reset() {
	*x = CSRspBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspBody) ProtoMessage() {}

func (x *CSRspBody) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspBody.ProtoReflect.Descriptor instead.
func (*CSRspBody) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

func (x *CSRspBody) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CSRspBody) GetErrCode() ERROR_CODE {
	if x != nil {
		return x.ErrCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *CSRspBody) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *CSRspBody) GetLogin() *CSRspLogin {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *CSRspBody) GetHeartbeat() *CSRspHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *CSRspBody) GetSetUsername() *CSRspSetUsername {
	if x != nil {
		return x.SetUsername
	}
	return nil
}

func (x *CSRspBody) GetRoomChat() *CSRspRoomChat {
	if x != nil {
		return x.RoomChat
	}
	return nil
}

func (x *CSRspBody) GetRoomList() *CSRspRoomList {
	if x != nil {
		return x.RoomList
	}
	return nil
}

func (x *CSRspBody) GetJoinRoom() *CSRspJoinRoom {
	if x != nil {
		return x.JoinRoom
	}
	return nil
}

type CSNtfBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kick             *CSNtfKick             `protobuf:"bytes,1,opt,name=Kick,proto3" json:"Kick,omitempty"`
	RoomMemberOnline *CSNtfRoomMemberOnline `protobuf:"bytes,2,opt,name=RoomMemberOnline,proto3" json:"RoomMemberOnline,omitempty"`
	RoomChat         *CSNtfRoomChat         `protobuf:"bytes,3,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomClosed       *CSNtfRoomClosed       `protobuf:"bytes,4,opt,name=RoomClosed,proto3" json:"RoomClosed,omitempty"`
	HistoryMsg       *CSNtfHistoryMsg       `protobuf:"bytes,5,opt,name=HistoryMsg,proto3" json:"HistoryMsg,omitempty"`
}

func (x *CSNtfBody) Reset() {
	*x = CSNtfBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfBody) ProtoMessage() {}

func (x *CSNtfBody) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfBody.ProtoReflect.Descriptor instead.
func (*CSNtfBody) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

func (x *CSNtfBody) GetKick() *CSNtfKick {
	if x != nil {
		return x.Kick
	}
	return nil
}

func (x *CSNtfBody) GetRoomMemberOnline() *CSNtfRoomMemberOnline {
	if x != nil {
		return x.RoomMemberOnline
	}
	return nil
}

func (x *CSNtfBody) GetRoomChat() *CSNtfRoomChat {
	if x != nil {
		return x.RoomChat
	}
	return nil
}

func (x *CSNtfBody) GetRoomClosed() *CSNtfRoomClosed {
	if x != nil {
		return x.RoomClosed
	}
	return nil
}

func (x *CSNtfBody) GetHistoryMsg() *CSNtfHistoryMsg {
	if x != nil {
		return x.HistoryMsg
	}
	return nil
}

type CSReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *CSReqLogin) Reset() {
	*x = CSReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqLogin) ProtoMessage() {}

func (x *CSReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqLogin.ProtoReflect.Descriptor instead.
func (*CSReqLogin) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

func (x *CSReqLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CSRspLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID   int64  `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *CSRspLogin) Reset() {
	*x = CSRspLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspLogin) ProtoMessage() {}

func (x *CSRspLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspLogin.ProtoReflect.Descriptor instead.
func (*CSRspLogin) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

func (x *CSRspLogin) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *CSRspLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CSReqHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSReqHeartbeat) Reset() {
	*x = CSReqHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqHeartbeat) ProtoMessage() {}

func (x *CSReqHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqHeartbeat.ProtoReflect.Descriptor instead.
func (*CSReqHeartbeat) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

type CSRspHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSRspHeartbeat) Reset() {
	*x = CSRspHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspHeartbeat) ProtoMessage() {}

func (x *CSRspHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspHeartbeat.ProtoReflect.Descriptor instead.
func (*CSRspHeartbeat) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

type CSReqSetUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *CSReqSetUsername) Reset() {
	*x = CSReqSetUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqSetUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqSetUsername) ProtoMessage() {}

func (x *CSReqSetUsername) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqSetUsername.ProtoReflect.Descriptor instead.
func (*CSReqSetUsername) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *CSReqSetUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CSRspSetUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSRspSetUsername) Reset() {
	*x = CSRspSetUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspSetUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspSetUsername) ProtoMessage() {}

func (x *CSRspSetUsername) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspSetUsername.ProtoReflect.Descriptor instead.
func (*CSRspSetUsername) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

type CSReqRoomChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CSReqRoomChat) Reset() {
	*x = CSReqRoomChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqRoomChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqRoomChat) ProtoMessage() {}

func (x *CSReqRoomChat) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqRoomChat.ProtoReflect.Descriptor instead.
func (*CSReqRoomChat) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{10}
}

func (x *CSReqRoomChat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CSRspRoomChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSRspRoomChat) Reset() {
	*x = CSRspRoomChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspRoomChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspRoomChat) ProtoMessage() {}

func (x *CSRspRoomChat) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspRoomChat.ProtoReflect.Descriptor instead.
func (*CSRspRoomChat) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{11}
}

type CSReqRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxRoomCount int32 `protobuf:"varint,1,opt,name=MaxRoomCount,proto3" json:"MaxRoomCount,omitempty"`
}

func (x *CSReqRoomList) Reset() {
	*x = CSReqRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqRoomList) ProtoMessage() {}

func (x *CSReqRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqRoomList.ProtoReflect.Descriptor instead.
func (*CSReqRoomList) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{12}
}

func (x *CSReqRoomList) GetMaxRoomCount() int32 {
	if x != nil {
		return x.MaxRoomCount
	}
	return 0
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentMemberNum int32 `protobuf:"varint,1,opt,name=CurrentMemberNum,proto3" json:"CurrentMemberNum,omitempty"`
	TotalMemberNum   int32 `protobuf:"varint,2,opt,name=TotalMemberNum,proto3" json:"TotalMemberNum,omitempty"`
	RoomID           int64 `protobuf:"varint,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{13}
}

func (x *RoomInfo) GetCurrentMemberNum() int32 {
	if x != nil {
		return x.CurrentMemberNum
	}
	return 0
}

func (x *RoomInfo) GetTotalMemberNum() int32 {
	if x != nil {
		return x.TotalMemberNum
	}
	return 0
}

func (x *RoomInfo) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type CSRspRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomInfo `protobuf:"bytes,1,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
}

func (x *CSRspRoomList) Reset() {
	*x = CSRspRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspRoomList) ProtoMessage() {}

func (x *CSRspRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspRoomList.ProtoReflect.Descriptor instead.
func (*CSRspRoomList) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{14}
}

func (x *CSRspRoomList) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type CSReqJoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID    int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	CreateNew bool  `protobuf:"varint,2,opt,name=CreateNew,proto3" json:"CreateNew,omitempty"`
}

func (x *CSReqJoinRoom) Reset() {
	*x = CSReqJoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReqJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReqJoinRoom) ProtoMessage() {}

func (x *CSReqJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReqJoinRoom.ProtoReflect.Descriptor instead.
func (*CSReqJoinRoom) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{15}
}

func (x *CSReqJoinRoom) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *CSReqJoinRoom) GetCreateNew() bool {
	if x != nil {
		return x.CreateNew
	}
	return false
}

type CSRspJoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSRspJoinRoom) Reset() {
	*x = CSRspJoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRspJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRspJoinRoom) ProtoMessage() {}

func (x *CSRspJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRspJoinRoom.ProtoReflect.Descriptor instead.
func (*CSRspJoinRoom) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{16}
}

type CSNtfKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSNtfKick) Reset() {
	*x = CSNtfKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfKick) ProtoMessage() {}

func (x *CSNtfKick) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfKick.ProtoReflect.Descriptor instead.
func (*CSNtfKick) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{17}
}

type CSNtfRoomMemberOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSNtfRoomMemberOnline) Reset() {
	*x = CSNtfRoomMemberOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfRoomMemberOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfRoomMemberOnline) ProtoMessage() {}

func (x *CSNtfRoomMemberOnline) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfRoomMemberOnline.ProtoReflect.Descriptor instead.
func (*CSNtfRoomMemberOnline) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{18}
}

type CSNtfRoomChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *CSNtfRoomChat) Reset() {
	*x = CSNtfRoomChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfRoomChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfRoomChat) ProtoMessage() {}

func (x *CSNtfRoomChat) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfRoomChat.ProtoReflect.Descriptor instead.
func (*CSNtfRoomChat) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{19}
}

func (x *CSNtfRoomChat) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CSNtfRoomChat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CSNtfRoomClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSNtfRoomClosed) Reset() {
	*x = CSNtfRoomClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfRoomClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfRoomClosed) ProtoMessage() {}

func (x *CSNtfRoomClosed) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfRoomClosed.ProtoReflect.Descriptor instead.
func (*CSNtfRoomClosed) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{20}
}

type CSNtfHistoryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History []string `protobuf:"bytes,1,rep,name=History,proto3" json:"History,omitempty"`
}

func (x *CSNtfHistoryMsg) Reset() {
	*x = CSNtfHistoryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSNtfHistoryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSNtfHistoryMsg) ProtoMessage() {}

func (x *CSNtfHistoryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSNtfHistoryMsg.ProtoReflect.Descriptor instead.
func (*CSNtfHistoryMsg) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{21}
}

func (x *CSNtfHistoryMsg) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x69,
	0x0a, 0x06, 0x43, 0x53, 0x48, 0x65, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x42, 0x6f,
	0x64, 0x79, 0x4c, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x49, 0x73, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x22, 0xba, 0x02, 0x0a, 0x09, 0x43, 0x53,
	0x52, 0x65, 0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x05, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53,
	0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x30, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x12, 0x36, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x52, 0x6f, 0x6f,
	0x6d, 0x43, 0x68, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x53, 0x52, 0x65, 0x71, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x52, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x53, 0x52, 0x65, 0x71, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x52,
	0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x6f, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x53, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0xfc, 0x02, 0x0a, 0x09, 0x43, 0x53, 0x52, 0x73, 0x70,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x24, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x52,
	0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x30,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x12, 0x36, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x52, 0x73, 0x70,
	0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x53, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x68, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x53, 0x52, 0x73, 0x70, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x52, 0x08, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x53, 0x52, 0x73, 0x70, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x52, 0x6f,
	0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53,
	0x52, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0x8e, 0x02, 0x0a, 0x09, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x4b, 0x69, 0x63, 0x6b,
	0x52, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x45, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52, 0x6f, 0x6f, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x10, 0x52, 0x6f, 0x6f,
	0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x2d, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x33, 0x0a, 0x0a,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x52, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x12, 0x33, 0x0a, 0x0a, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x53, 0x4e, 0x74, 0x66,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x0a, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x28, 0x0a, 0x0a, 0x43, 0x53, 0x52, 0x65, 0x71, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x40, 0x0a, 0x0a, 0x43, 0x53, 0x52, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x53, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x53, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x2e, 0x0a, 0x10, 0x43, 0x53, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x53, 0x52, 0x73, 0x70, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x43, 0x53,
	0x52, 0x65, 0x71, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x53, 0x52, 0x73, 0x70, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x22, 0x33, 0x0a, 0x0d, 0x43, 0x53, 0x52, 0x65, 0x71, 0x52,
	0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x61, 0x78, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4d,
	0x61, 0x78, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x76, 0x0a, 0x08, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x0d, 0x43, 0x53, 0x52, 0x73, 0x70, 0x52, 0x6f, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x53, 0x52, 0x65,
	0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x22,
	0x0f, 0x0a, 0x0d, 0x43, 0x53, 0x52, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x22, 0x0b, 0x0a, 0x09, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x4b, 0x69, 0x63, 0x6b, 0x22, 0x17, 0x0a,
	0x15, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a,
	0x0f, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x53, 0x4e, 0x74, 0x66, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2a, 0x25, 0x0a,
	0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x01, 0x2a, 0xf6, 0x02, 0x0a, 0x07, 0x43, 0x53, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x52, 0x45, 0x51, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10,
	0x02, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x55, 0x53, 0x45,
	0x52, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x5f, 0x52,
	0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45,
	0x51, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x45, 0x51, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x06,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x53, 0x50, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x64, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x53, 0x50, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x65, 0x12, 0x11,
	0x0a, 0x0d, 0x52, 0x53, 0x50, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10,
	0x66, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x53, 0x50, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x55, 0x53, 0x45,
	0x52, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x67, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x53, 0x50, 0x5f, 0x52,
	0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x68, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x53,
	0x50, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x69, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x53, 0x50, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x6a,
	0x12, 0x0e, 0x0a, 0x09, 0x4e, 0x54, 0x46, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0xc8, 0x01,
	0x12, 0x1b, 0x0a, 0x16, 0x4e, 0x54, 0x46, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4d, 0x45, 0x4d,
	0x42, 0x45, 0x52, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0xc9, 0x01, 0x12, 0x12, 0x0a,
	0x0d, 0x4e, 0x54, 0x46, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0xca,
	0x01, 0x12, 0x14, 0x0a, 0x0f, 0x4e, 0x54, 0x46, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x44, 0x10, 0xcb, 0x01, 0x12, 0x14, 0x0a, 0x0f, 0x4e, 0x54, 0x46, 0x5f, 0x48,
	0x49, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0xcc, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cs_proto_goTypes = []interface{}{
	(ERROR_CODE)(0),               // 0: pb.ERROR_CODE
	(CSMsgID)(0),                  // 1: pb.CSMsgID
	(*CSHead)(nil),                // 2: pb.CSHead
	(*CSReqBody)(nil),             // 3: pb.CSReqBody
	(*CSRspBody)(nil),             // 4: pb.CSRspBody
	(*CSNtfBody)(nil),             // 5: pb.CSNtfBody
	(*CSReqLogin)(nil),            // 6: pb.CSReqLogin
	(*CSRspLogin)(nil),            // 7: pb.CSRspLogin
	(*CSReqHeartbeat)(nil),        // 8: pb.CSReqHeartbeat
	(*CSRspHeartbeat)(nil),        // 9: pb.CSRspHeartbeat
	(*CSReqSetUsername)(nil),      // 10: pb.CSReqSetUsername
	(*CSRspSetUsername)(nil),      // 11: pb.CSRspSetUsername
	(*CSReqRoomChat)(nil),         // 12: pb.CSReqRoomChat
	(*CSRspRoomChat)(nil),         // 13: pb.CSRspRoomChat
	(*CSReqRoomList)(nil),         // 14: pb.CSReqRoomList
	(*RoomInfo)(nil),              // 15: pb.RoomInfo
	(*CSRspRoomList)(nil),         // 16: pb.CSRspRoomList
	(*CSReqJoinRoom)(nil),         // 17: pb.CSReqJoinRoom
	(*CSRspJoinRoom)(nil),         // 18: pb.CSRspJoinRoom
	(*CSNtfKick)(nil),             // 19: pb.CSNtfKick
	(*CSNtfRoomMemberOnline)(nil), // 20: pb.CSNtfRoomMemberOnline
	(*CSNtfRoomChat)(nil),         // 21: pb.CSNtfRoomChat
	(*CSNtfRoomClosed)(nil),       // 22: pb.CSNtfRoomClosed
	(*CSNtfHistoryMsg)(nil),       // 23: pb.CSNtfHistoryMsg
}
var file_cs_proto_depIdxs = []int32{
	1,  // 0: pb.CSHead.MsgID:type_name -> pb.CSMsgID
	6,  // 1: pb.CSReqBody.Login:type_name -> pb.CSReqLogin
	8,  // 2: pb.CSReqBody.Heartbeat:type_name -> pb.CSReqHeartbeat
	10, // 3: pb.CSReqBody.SetUsername:type_name -> pb.CSReqSetUsername
	12, // 4: pb.CSReqBody.RoomChat:type_name -> pb.CSReqRoomChat
	14, // 5: pb.CSReqBody.RoomList:type_name -> pb.CSReqRoomList
	17, // 6: pb.CSReqBody.JoinRoom:type_name -> pb.CSReqJoinRoom
	0,  // 7: pb.CSRspBody.ErrCode:type_name -> pb.ERROR_CODE
	7,  // 8: pb.CSRspBody.Login:type_name -> pb.CSRspLogin
	9,  // 9: pb.CSRspBody.Heartbeat:type_name -> pb.CSRspHeartbeat
	11, // 10: pb.CSRspBody.SetUsername:type_name -> pb.CSRspSetUsername
	13, // 11: pb.CSRspBody.RoomChat:type_name -> pb.CSRspRoomChat
	16, // 12: pb.CSRspBody.RoomList:type_name -> pb.CSRspRoomList
	18, // 13: pb.CSRspBody.JoinRoom:type_name -> pb.CSRspJoinRoom
	19, // 14: pb.CSNtfBody.Kick:type_name -> pb.CSNtfKick
	20, // 15: pb.CSNtfBody.RoomMemberOnline:type_name -> pb.CSNtfRoomMemberOnline
	21, // 16: pb.CSNtfBody.RoomChat:type_name -> pb.CSNtfRoomChat
	22, // 17: pb.CSNtfBody.RoomClosed:type_name -> pb.CSNtfRoomClosed
	23, // 18: pb.CSNtfBody.HistoryMsg:type_name -> pb.CSNtfHistoryMsg
	15, // 19: pb.CSRspRoomList.Rooms:type_name -> pb.RoomInfo
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqSetUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspSetUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqRoomChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspRoomChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReqJoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRspJoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfRoomMemberOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfRoomChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfRoomClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSNtfHistoryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		EnumInfos:         file_cs_proto_enumTypes,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
