// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ERROR_CODE int32

const (
	ERROR_CODE_SUCCESS ERROR_CODE = 0
	ERROR_CODE_FAILED  ERROR_CODE = 1
)

var ERROR_CODE_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}

var ERROR_CODE_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x ERROR_CODE) String() string {
	return proto.EnumName(ERROR_CODE_name, int32(x))
}

func (ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

type CSMsgID int32

const (
	CSMsgID_REQ_BEGIN              CSMsgID = 0
	CSMsgID_REQ_LOGIN              CSMsgID = 1
	CSMsgID_REQ_HEARTBEAT          CSMsgID = 2
	CSMsgID_REQ_SET_USERNAME       CSMsgID = 3
	CSMsgID_REQ_ROOM_CHAT          CSMsgID = 4
	CSMsgID_REQ_ROOM_LIST          CSMsgID = 5
	CSMsgID_REQ_JOIN_ROOM          CSMsgID = 6
	CSMsgID_RSP_BEGIN              CSMsgID = 100
	CSMsgID_RSP_LOGIN              CSMsgID = 101
	CSMsgID_RSP_HEARTBEAT          CSMsgID = 102
	CSMsgID_RSP_SET_USERNAME       CSMsgID = 103
	CSMsgID_RSP_ROOM_CHAT          CSMsgID = 104
	CSMsgID_RSP_ROOM_LIST          CSMsgID = 105
	CSMsgID_RSP_JOIN_ROOM          CSMsgID = 106
	CSMsgID_NTF_BEGIN              CSMsgID = 200
	CSMsgID_NTF_ROOM_MEMBER_ONLINE CSMsgID = 201
	CSMsgID_NTF_ROOM_CHAT          CSMsgID = 202
	CSMsgID_NTF_ROOM_CLOSED        CSMsgID = 203
	CSMsgID_NTF_HISTROY_MSG        CSMsgID = 204
)

var CSMsgID_name = map[int32]string{
	0:   "REQ_BEGIN",
	1:   "REQ_LOGIN",
	2:   "REQ_HEARTBEAT",
	3:   "REQ_SET_USERNAME",
	4:   "REQ_ROOM_CHAT",
	5:   "REQ_ROOM_LIST",
	6:   "REQ_JOIN_ROOM",
	100: "RSP_BEGIN",
	101: "RSP_LOGIN",
	102: "RSP_HEARTBEAT",
	103: "RSP_SET_USERNAME",
	104: "RSP_ROOM_CHAT",
	105: "RSP_ROOM_LIST",
	106: "RSP_JOIN_ROOM",
	200: "NTF_BEGIN",
	201: "NTF_ROOM_MEMBER_ONLINE",
	202: "NTF_ROOM_CHAT",
	203: "NTF_ROOM_CLOSED",
	204: "NTF_HISTROY_MSG",
}

var CSMsgID_value = map[string]int32{
	"REQ_BEGIN":              0,
	"REQ_LOGIN":              1,
	"REQ_HEARTBEAT":          2,
	"REQ_SET_USERNAME":       3,
	"REQ_ROOM_CHAT":          4,
	"REQ_ROOM_LIST":          5,
	"REQ_JOIN_ROOM":          6,
	"RSP_BEGIN":              100,
	"RSP_LOGIN":              101,
	"RSP_HEARTBEAT":          102,
	"RSP_SET_USERNAME":       103,
	"RSP_ROOM_CHAT":          104,
	"RSP_ROOM_LIST":          105,
	"RSP_JOIN_ROOM":          106,
	"NTF_BEGIN":              200,
	"NTF_ROOM_MEMBER_ONLINE": 201,
	"NTF_ROOM_CHAT":          202,
	"NTF_ROOM_CLOSED":        203,
	"NTF_HISTROY_MSG":        204,
}

func (x CSMsgID) String() string {
	return proto.EnumName(CSMsgID_name, int32(x))
}

func (CSMsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{1}
}

type CSHead struct {
	MsgID                CSMsgID  `protobuf:"varint,1,opt,name=MsgID,proto3,enum=pb.CSMsgID" json:"MsgID,omitempty"`
	BodyLen              int32    `protobuf:"varint,2,opt,name=BodyLen,proto3" json:"BodyLen,omitempty"`
	IsCompressed         bool     `protobuf:"varint,3,opt,name=IsCompressed,proto3" json:"IsCompressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSHead) Reset()         { *m = CSHead{} }
func (m *CSHead) String() string { return proto.CompactTextString(m) }
func (*CSHead) ProtoMessage()    {}
func (*CSHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

func (m *CSHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSHead.Unmarshal(m, b)
}
func (m *CSHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSHead.Marshal(b, m, deterministic)
}
func (m *CSHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSHead.Merge(m, src)
}
func (m *CSHead) XXX_Size() int {
	return xxx_messageInfo_CSHead.Size(m)
}
func (m *CSHead) XXX_DiscardUnknown() {
	xxx_messageInfo_CSHead.DiscardUnknown(m)
}

var xxx_messageInfo_CSHead proto.InternalMessageInfo

func (m *CSHead) GetMsgID() CSMsgID {
	if m != nil {
		return m.MsgID
	}
	return CSMsgID_REQ_BEGIN
}

func (m *CSHead) GetBodyLen() int32 {
	if m != nil {
		return m.BodyLen
	}
	return 0
}

func (m *CSHead) GetIsCompressed() bool {
	if m != nil {
		return m.IsCompressed
	}
	return false
}

type CSReqBody struct {
	Seq                  int64             `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Login                *CSReqLogin       `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	Heartbeat            *CSReqHeartbeat   `protobuf:"bytes,3,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"`
	SetUsername          *CSReqSetUsername `protobuf:"bytes,4,opt,name=SetUsername,proto3" json:"SetUsername,omitempty"`
	RoomChat             *CSReqRoomChat    `protobuf:"bytes,5,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomList             *CSReqRoomList    `protobuf:"bytes,6,opt,name=RoomList,proto3" json:"RoomList,omitempty"`
	JoinRoom             *CSReqJoinRoom    `protobuf:"bytes,7,opt,name=JoinRoom,proto3" json:"JoinRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CSReqBody) Reset()         { *m = CSReqBody{} }
func (m *CSReqBody) String() string { return proto.CompactTextString(m) }
func (*CSReqBody) ProtoMessage()    {}
func (*CSReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{1}
}

func (m *CSReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqBody.Unmarshal(m, b)
}
func (m *CSReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqBody.Marshal(b, m, deterministic)
}
func (m *CSReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqBody.Merge(m, src)
}
func (m *CSReqBody) XXX_Size() int {
	return xxx_messageInfo_CSReqBody.Size(m)
}
func (m *CSReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqBody proto.InternalMessageInfo

func (m *CSReqBody) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CSReqBody) GetLogin() *CSReqLogin {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *CSReqBody) GetHeartbeat() *CSReqHeartbeat {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

func (m *CSReqBody) GetSetUsername() *CSReqSetUsername {
	if m != nil {
		return m.SetUsername
	}
	return nil
}

func (m *CSReqBody) GetRoomChat() *CSReqRoomChat {
	if m != nil {
		return m.RoomChat
	}
	return nil
}

func (m *CSReqBody) GetRoomList() *CSReqRoomList {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *CSReqBody) GetJoinRoom() *CSReqJoinRoom {
	if m != nil {
		return m.JoinRoom
	}
	return nil
}

type CSRspBody struct {
	Seq                  int64             `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	ErrCode              ERROR_CODE        `protobuf:"varint,2,opt,name=ErrCode,proto3,enum=pb.ERROR_CODE" json:"ErrCode,omitempty"`
	ErrMsg               string            `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Login                *CSRspLogin       `protobuf:"bytes,4,opt,name=Login,proto3" json:"Login,omitempty"`
	Heartbeat            *CSRspHeartbeat   `protobuf:"bytes,5,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"`
	SetUsername          *CSRspSetUsername `protobuf:"bytes,6,opt,name=SetUsername,proto3" json:"SetUsername,omitempty"`
	RoomChat             *CSRspRoomChat    `protobuf:"bytes,7,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomList             *CSRspRoomList    `protobuf:"bytes,8,opt,name=RoomList,proto3" json:"RoomList,omitempty"`
	JoinRoom             *CSRspJoinRoom    `protobuf:"bytes,9,opt,name=JoinRoom,proto3" json:"JoinRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CSRspBody) Reset()         { *m = CSRspBody{} }
func (m *CSRspBody) String() string { return proto.CompactTextString(m) }
func (*CSRspBody) ProtoMessage()    {}
func (*CSRspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{2}
}

func (m *CSRspBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspBody.Unmarshal(m, b)
}
func (m *CSRspBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspBody.Marshal(b, m, deterministic)
}
func (m *CSRspBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspBody.Merge(m, src)
}
func (m *CSRspBody) XXX_Size() int {
	return xxx_messageInfo_CSRspBody.Size(m)
}
func (m *CSRspBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspBody.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspBody proto.InternalMessageInfo

func (m *CSRspBody) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CSRspBody) GetErrCode() ERROR_CODE {
	if m != nil {
		return m.ErrCode
	}
	return ERROR_CODE_SUCCESS
}

func (m *CSRspBody) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CSRspBody) GetLogin() *CSRspLogin {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *CSRspBody) GetHeartbeat() *CSRspHeartbeat {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

func (m *CSRspBody) GetSetUsername() *CSRspSetUsername {
	if m != nil {
		return m.SetUsername
	}
	return nil
}

func (m *CSRspBody) GetRoomChat() *CSRspRoomChat {
	if m != nil {
		return m.RoomChat
	}
	return nil
}

func (m *CSRspBody) GetRoomList() *CSRspRoomList {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *CSRspBody) GetJoinRoom() *CSRspJoinRoom {
	if m != nil {
		return m.JoinRoom
	}
	return nil
}

type CSNtfBody struct {
	Kick                 *CSNtfKick             `protobuf:"bytes,1,opt,name=Kick,proto3" json:"Kick,omitempty"`
	RoomMemberOnline     *CSNtfRoomMemberOnline `protobuf:"bytes,2,opt,name=RoomMemberOnline,proto3" json:"RoomMemberOnline,omitempty"`
	RoomChat             *CSNtfRoomChat         `protobuf:"bytes,3,opt,name=RoomChat,proto3" json:"RoomChat,omitempty"`
	RoomClosed           *CSNtfRoomClosed       `protobuf:"bytes,4,opt,name=RoomClosed,proto3" json:"RoomClosed,omitempty"`
	HistoryMsg           *CSNtfHistoryMsg       `protobuf:"bytes,5,opt,name=HistoryMsg,proto3" json:"HistoryMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CSNtfBody) Reset()         { *m = CSNtfBody{} }
func (m *CSNtfBody) String() string { return proto.CompactTextString(m) }
func (*CSNtfBody) ProtoMessage()    {}
func (*CSNtfBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{3}
}

func (m *CSNtfBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfBody.Unmarshal(m, b)
}
func (m *CSNtfBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfBody.Marshal(b, m, deterministic)
}
func (m *CSNtfBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfBody.Merge(m, src)
}
func (m *CSNtfBody) XXX_Size() int {
	return xxx_messageInfo_CSNtfBody.Size(m)
}
func (m *CSNtfBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfBody.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfBody proto.InternalMessageInfo

func (m *CSNtfBody) GetKick() *CSNtfKick {
	if m != nil {
		return m.Kick
	}
	return nil
}

func (m *CSNtfBody) GetRoomMemberOnline() *CSNtfRoomMemberOnline {
	if m != nil {
		return m.RoomMemberOnline
	}
	return nil
}

func (m *CSNtfBody) GetRoomChat() *CSNtfRoomChat {
	if m != nil {
		return m.RoomChat
	}
	return nil
}

func (m *CSNtfBody) GetRoomClosed() *CSNtfRoomClosed {
	if m != nil {
		return m.RoomClosed
	}
	return nil
}

func (m *CSNtfBody) GetHistoryMsg() *CSNtfHistoryMsg {
	if m != nil {
		return m.HistoryMsg
	}
	return nil
}

type CSReqLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqLogin) Reset()         { *m = CSReqLogin{} }
func (m *CSReqLogin) String() string { return proto.CompactTextString(m) }
func (*CSReqLogin) ProtoMessage()    {}
func (*CSReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{4}
}

func (m *CSReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqLogin.Unmarshal(m, b)
}
func (m *CSReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqLogin.Marshal(b, m, deterministic)
}
func (m *CSReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqLogin.Merge(m, src)
}
func (m *CSReqLogin) XXX_Size() int {
	return xxx_messageInfo_CSReqLogin.Size(m)
}
func (m *CSReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqLogin proto.InternalMessageInfo

func (m *CSReqLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CSRspLogin struct {
	RoomID               int64    `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSRspLogin) Reset()         { *m = CSRspLogin{} }
func (m *CSRspLogin) String() string { return proto.CompactTextString(m) }
func (*CSRspLogin) ProtoMessage()    {}
func (*CSRspLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{5}
}

func (m *CSRspLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspLogin.Unmarshal(m, b)
}
func (m *CSRspLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspLogin.Marshal(b, m, deterministic)
}
func (m *CSRspLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspLogin.Merge(m, src)
}
func (m *CSRspLogin) XXX_Size() int {
	return xxx_messageInfo_CSRspLogin.Size(m)
}
func (m *CSRspLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspLogin proto.InternalMessageInfo

func (m *CSRspLogin) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *CSRspLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CSReqHeartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqHeartbeat) Reset()         { *m = CSReqHeartbeat{} }
func (m *CSReqHeartbeat) String() string { return proto.CompactTextString(m) }
func (*CSReqHeartbeat) ProtoMessage()    {}
func (*CSReqHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{6}
}

func (m *CSReqHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqHeartbeat.Unmarshal(m, b)
}
func (m *CSReqHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqHeartbeat.Marshal(b, m, deterministic)
}
func (m *CSReqHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqHeartbeat.Merge(m, src)
}
func (m *CSReqHeartbeat) XXX_Size() int {
	return xxx_messageInfo_CSReqHeartbeat.Size(m)
}
func (m *CSReqHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqHeartbeat proto.InternalMessageInfo

type CSRspHeartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSRspHeartbeat) Reset()         { *m = CSRspHeartbeat{} }
func (m *CSRspHeartbeat) String() string { return proto.CompactTextString(m) }
func (*CSRspHeartbeat) ProtoMessage()    {}
func (*CSRspHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{7}
}

func (m *CSRspHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspHeartbeat.Unmarshal(m, b)
}
func (m *CSRspHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspHeartbeat.Marshal(b, m, deterministic)
}
func (m *CSRspHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspHeartbeat.Merge(m, src)
}
func (m *CSRspHeartbeat) XXX_Size() int {
	return xxx_messageInfo_CSRspHeartbeat.Size(m)
}
func (m *CSRspHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspHeartbeat proto.InternalMessageInfo

type CSReqSetUsername struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqSetUsername) Reset()         { *m = CSReqSetUsername{} }
func (m *CSReqSetUsername) String() string { return proto.CompactTextString(m) }
func (*CSReqSetUsername) ProtoMessage()    {}
func (*CSReqSetUsername) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{8}
}

func (m *CSReqSetUsername) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqSetUsername.Unmarshal(m, b)
}
func (m *CSReqSetUsername) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqSetUsername.Marshal(b, m, deterministic)
}
func (m *CSReqSetUsername) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqSetUsername.Merge(m, src)
}
func (m *CSReqSetUsername) XXX_Size() int {
	return xxx_messageInfo_CSReqSetUsername.Size(m)
}
func (m *CSReqSetUsername) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqSetUsername.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqSetUsername proto.InternalMessageInfo

func (m *CSReqSetUsername) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CSRspSetUsername struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSRspSetUsername) Reset()         { *m = CSRspSetUsername{} }
func (m *CSRspSetUsername) String() string { return proto.CompactTextString(m) }
func (*CSRspSetUsername) ProtoMessage()    {}
func (*CSRspSetUsername) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{9}
}

func (m *CSRspSetUsername) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspSetUsername.Unmarshal(m, b)
}
func (m *CSRspSetUsername) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspSetUsername.Marshal(b, m, deterministic)
}
func (m *CSRspSetUsername) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspSetUsername.Merge(m, src)
}
func (m *CSRspSetUsername) XXX_Size() int {
	return xxx_messageInfo_CSRspSetUsername.Size(m)
}
func (m *CSRspSetUsername) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspSetUsername.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspSetUsername proto.InternalMessageInfo

type CSReqRoomChat struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqRoomChat) Reset()         { *m = CSReqRoomChat{} }
func (m *CSReqRoomChat) String() string { return proto.CompactTextString(m) }
func (*CSReqRoomChat) ProtoMessage()    {}
func (*CSReqRoomChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{10}
}

func (m *CSReqRoomChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqRoomChat.Unmarshal(m, b)
}
func (m *CSReqRoomChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqRoomChat.Marshal(b, m, deterministic)
}
func (m *CSReqRoomChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqRoomChat.Merge(m, src)
}
func (m *CSReqRoomChat) XXX_Size() int {
	return xxx_messageInfo_CSReqRoomChat.Size(m)
}
func (m *CSReqRoomChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqRoomChat.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqRoomChat proto.InternalMessageInfo

func (m *CSReqRoomChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CSRspRoomChat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSRspRoomChat) Reset()         { *m = CSRspRoomChat{} }
func (m *CSRspRoomChat) String() string { return proto.CompactTextString(m) }
func (*CSRspRoomChat) ProtoMessage()    {}
func (*CSRspRoomChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{11}
}

func (m *CSRspRoomChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspRoomChat.Unmarshal(m, b)
}
func (m *CSRspRoomChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspRoomChat.Marshal(b, m, deterministic)
}
func (m *CSRspRoomChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspRoomChat.Merge(m, src)
}
func (m *CSRspRoomChat) XXX_Size() int {
	return xxx_messageInfo_CSRspRoomChat.Size(m)
}
func (m *CSRspRoomChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspRoomChat.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspRoomChat proto.InternalMessageInfo

type CSReqRoomList struct {
	MaxRoomCount         int32    `protobuf:"varint,1,opt,name=MaxRoomCount,proto3" json:"MaxRoomCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqRoomList) Reset()         { *m = CSReqRoomList{} }
func (m *CSReqRoomList) String() string { return proto.CompactTextString(m) }
func (*CSReqRoomList) ProtoMessage()    {}
func (*CSReqRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{12}
}

func (m *CSReqRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqRoomList.Unmarshal(m, b)
}
func (m *CSReqRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqRoomList.Marshal(b, m, deterministic)
}
func (m *CSReqRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqRoomList.Merge(m, src)
}
func (m *CSReqRoomList) XXX_Size() int {
	return xxx_messageInfo_CSReqRoomList.Size(m)
}
func (m *CSReqRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqRoomList proto.InternalMessageInfo

func (m *CSReqRoomList) GetMaxRoomCount() int32 {
	if m != nil {
		return m.MaxRoomCount
	}
	return 0
}

type RoomInfo struct {
	CurrentMemberNum     int32    `protobuf:"varint,1,opt,name=CurrentMemberNum,proto3" json:"CurrentMemberNum,omitempty"`
	TotalMemberNum       int32    `protobuf:"varint,2,opt,name=TotalMemberNum,proto3" json:"TotalMemberNum,omitempty"`
	RoomID               int64    `protobuf:"varint,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{13}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetCurrentMemberNum() int32 {
	if m != nil {
		return m.CurrentMemberNum
	}
	return 0
}

func (m *RoomInfo) GetTotalMemberNum() int32 {
	if m != nil {
		return m.TotalMemberNum
	}
	return 0
}

func (m *RoomInfo) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type CSRspRoomList struct {
	Rooms                []*RoomInfo `protobuf:"bytes,1,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CSRspRoomList) Reset()         { *m = CSRspRoomList{} }
func (m *CSRspRoomList) String() string { return proto.CompactTextString(m) }
func (*CSRspRoomList) ProtoMessage()    {}
func (*CSRspRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{14}
}

func (m *CSRspRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspRoomList.Unmarshal(m, b)
}
func (m *CSRspRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspRoomList.Marshal(b, m, deterministic)
}
func (m *CSRspRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspRoomList.Merge(m, src)
}
func (m *CSRspRoomList) XXX_Size() int {
	return xxx_messageInfo_CSRspRoomList.Size(m)
}
func (m *CSRspRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspRoomList proto.InternalMessageInfo

func (m *CSRspRoomList) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type CSReqJoinRoom struct {
	RoomID               int64    `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	CreateNew            bool     `protobuf:"varint,2,opt,name=CreateNew,proto3" json:"CreateNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReqJoinRoom) Reset()         { *m = CSReqJoinRoom{} }
func (m *CSReqJoinRoom) String() string { return proto.CompactTextString(m) }
func (*CSReqJoinRoom) ProtoMessage()    {}
func (*CSReqJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{15}
}

func (m *CSReqJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReqJoinRoom.Unmarshal(m, b)
}
func (m *CSReqJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReqJoinRoom.Marshal(b, m, deterministic)
}
func (m *CSReqJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReqJoinRoom.Merge(m, src)
}
func (m *CSReqJoinRoom) XXX_Size() int {
	return xxx_messageInfo_CSReqJoinRoom.Size(m)
}
func (m *CSReqJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReqJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CSReqJoinRoom proto.InternalMessageInfo

func (m *CSReqJoinRoom) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *CSReqJoinRoom) GetCreateNew() bool {
	if m != nil {
		return m.CreateNew
	}
	return false
}

type CSRspJoinRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSRspJoinRoom) Reset()         { *m = CSRspJoinRoom{} }
func (m *CSRspJoinRoom) String() string { return proto.CompactTextString(m) }
func (*CSRspJoinRoom) ProtoMessage()    {}
func (*CSRspJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{16}
}

func (m *CSRspJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRspJoinRoom.Unmarshal(m, b)
}
func (m *CSRspJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRspJoinRoom.Marshal(b, m, deterministic)
}
func (m *CSRspJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRspJoinRoom.Merge(m, src)
}
func (m *CSRspJoinRoom) XXX_Size() int {
	return xxx_messageInfo_CSRspJoinRoom.Size(m)
}
func (m *CSRspJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRspJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CSRspJoinRoom proto.InternalMessageInfo

type CSNtfKick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSNtfKick) Reset()         { *m = CSNtfKick{} }
func (m *CSNtfKick) String() string { return proto.CompactTextString(m) }
func (*CSNtfKick) ProtoMessage()    {}
func (*CSNtfKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{17}
}

func (m *CSNtfKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfKick.Unmarshal(m, b)
}
func (m *CSNtfKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfKick.Marshal(b, m, deterministic)
}
func (m *CSNtfKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfKick.Merge(m, src)
}
func (m *CSNtfKick) XXX_Size() int {
	return xxx_messageInfo_CSNtfKick.Size(m)
}
func (m *CSNtfKick) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfKick.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfKick proto.InternalMessageInfo

type CSNtfRoomMemberOnline struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSNtfRoomMemberOnline) Reset()         { *m = CSNtfRoomMemberOnline{} }
func (m *CSNtfRoomMemberOnline) String() string { return proto.CompactTextString(m) }
func (*CSNtfRoomMemberOnline) ProtoMessage()    {}
func (*CSNtfRoomMemberOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{18}
}

func (m *CSNtfRoomMemberOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfRoomMemberOnline.Unmarshal(m, b)
}
func (m *CSNtfRoomMemberOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfRoomMemberOnline.Marshal(b, m, deterministic)
}
func (m *CSNtfRoomMemberOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfRoomMemberOnline.Merge(m, src)
}
func (m *CSNtfRoomMemberOnline) XXX_Size() int {
	return xxx_messageInfo_CSNtfRoomMemberOnline.Size(m)
}
func (m *CSNtfRoomMemberOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfRoomMemberOnline.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfRoomMemberOnline proto.InternalMessageInfo

type CSNtfRoomChat struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSNtfRoomChat) Reset()         { *m = CSNtfRoomChat{} }
func (m *CSNtfRoomChat) String() string { return proto.CompactTextString(m) }
func (*CSNtfRoomChat) ProtoMessage()    {}
func (*CSNtfRoomChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{19}
}

func (m *CSNtfRoomChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfRoomChat.Unmarshal(m, b)
}
func (m *CSNtfRoomChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfRoomChat.Marshal(b, m, deterministic)
}
func (m *CSNtfRoomChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfRoomChat.Merge(m, src)
}
func (m *CSNtfRoomChat) XXX_Size() int {
	return xxx_messageInfo_CSNtfRoomChat.Size(m)
}
func (m *CSNtfRoomChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfRoomChat.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfRoomChat proto.InternalMessageInfo

func (m *CSNtfRoomChat) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CSNtfRoomChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CSNtfRoomClosed struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSNtfRoomClosed) Reset()         { *m = CSNtfRoomClosed{} }
func (m *CSNtfRoomClosed) String() string { return proto.CompactTextString(m) }
func (*CSNtfRoomClosed) ProtoMessage()    {}
func (*CSNtfRoomClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{20}
}

func (m *CSNtfRoomClosed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfRoomClosed.Unmarshal(m, b)
}
func (m *CSNtfRoomClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfRoomClosed.Marshal(b, m, deterministic)
}
func (m *CSNtfRoomClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfRoomClosed.Merge(m, src)
}
func (m *CSNtfRoomClosed) XXX_Size() int {
	return xxx_messageInfo_CSNtfRoomClosed.Size(m)
}
func (m *CSNtfRoomClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfRoomClosed.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfRoomClosed proto.InternalMessageInfo

type HistoryChat struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Dt                   string   `protobuf:"bytes,2,opt,name=dt,proto3" json:"dt,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryChat) Reset()         { *m = HistoryChat{} }
func (m *HistoryChat) String() string { return proto.CompactTextString(m) }
func (*HistoryChat) ProtoMessage()    {}
func (*HistoryChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{21}
}

func (m *HistoryChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryChat.Unmarshal(m, b)
}
func (m *HistoryChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryChat.Marshal(b, m, deterministic)
}
func (m *HistoryChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryChat.Merge(m, src)
}
func (m *HistoryChat) XXX_Size() int {
	return xxx_messageInfo_HistoryChat.Size(m)
}
func (m *HistoryChat) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryChat.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryChat proto.InternalMessageInfo

func (m *HistoryChat) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HistoryChat) GetDt() string {
	if m != nil {
		return m.Dt
	}
	return ""
}

func (m *HistoryChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CSNtfHistoryMsg struct {
	History              []*HistoryChat `protobuf:"bytes,1,rep,name=History,proto3" json:"History,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CSNtfHistoryMsg) Reset()         { *m = CSNtfHistoryMsg{} }
func (m *CSNtfHistoryMsg) String() string { return proto.CompactTextString(m) }
func (*CSNtfHistoryMsg) ProtoMessage()    {}
func (*CSNtfHistoryMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{22}
}

func (m *CSNtfHistoryMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSNtfHistoryMsg.Unmarshal(m, b)
}
func (m *CSNtfHistoryMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSNtfHistoryMsg.Marshal(b, m, deterministic)
}
func (m *CSNtfHistoryMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSNtfHistoryMsg.Merge(m, src)
}
func (m *CSNtfHistoryMsg) XXX_Size() int {
	return xxx_messageInfo_CSNtfHistoryMsg.Size(m)
}
func (m *CSNtfHistoryMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CSNtfHistoryMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CSNtfHistoryMsg proto.InternalMessageInfo

func (m *CSNtfHistoryMsg) GetHistory() []*HistoryChat {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ERROR_CODE", ERROR_CODE_name, ERROR_CODE_value)
	proto.RegisterEnum("pb.CSMsgID", CSMsgID_name, CSMsgID_value)
	proto.RegisterType((*CSHead)(nil), "pb.CSHead")
	proto.RegisterType((*CSReqBody)(nil), "pb.CSReqBody")
	proto.RegisterType((*CSRspBody)(nil), "pb.CSRspBody")
	proto.RegisterType((*CSNtfBody)(nil), "pb.CSNtfBody")
	proto.RegisterType((*CSReqLogin)(nil), "pb.CSReqLogin")
	proto.RegisterType((*CSRspLogin)(nil), "pb.CSRspLogin")
	proto.RegisterType((*CSReqHeartbeat)(nil), "pb.CSReqHeartbeat")
	proto.RegisterType((*CSRspHeartbeat)(nil), "pb.CSRspHeartbeat")
	proto.RegisterType((*CSReqSetUsername)(nil), "pb.CSReqSetUsername")
	proto.RegisterType((*CSRspSetUsername)(nil), "pb.CSRspSetUsername")
	proto.RegisterType((*CSReqRoomChat)(nil), "pb.CSReqRoomChat")
	proto.RegisterType((*CSRspRoomChat)(nil), "pb.CSRspRoomChat")
	proto.RegisterType((*CSReqRoomList)(nil), "pb.CSReqRoomList")
	proto.RegisterType((*RoomInfo)(nil), "pb.RoomInfo")
	proto.RegisterType((*CSRspRoomList)(nil), "pb.CSRspRoomList")
	proto.RegisterType((*CSReqJoinRoom)(nil), "pb.CSReqJoinRoom")
	proto.RegisterType((*CSRspJoinRoom)(nil), "pb.CSRspJoinRoom")
	proto.RegisterType((*CSNtfKick)(nil), "pb.CSNtfKick")
	proto.RegisterType((*CSNtfRoomMemberOnline)(nil), "pb.CSNtfRoomMemberOnline")
	proto.RegisterType((*CSNtfRoomChat)(nil), "pb.CSNtfRoomChat")
	proto.RegisterType((*CSNtfRoomClosed)(nil), "pb.CSNtfRoomClosed")
	proto.RegisterType((*HistoryChat)(nil), "pb.HistoryChat")
	proto.RegisterType((*CSNtfHistoryMsg)(nil), "pb.CSNtfHistoryMsg")
}

func init() { proto.RegisterFile("cs.proto", fileDescriptor_af7bf51985781725) }

var fileDescriptor_af7bf51985781725 = []byte{
	// 948 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcb, 0x72, 0xdb, 0xc6,
	0x12, 0x35, 0x08, 0x82, 0x8f, 0x86, 0x48, 0x41, 0x73, 0x75, 0x1d, 0xe4, 0xb1, 0x90, 0x51, 0x49,
	0x8a, 0x56, 0x55, 0x54, 0x29, 0xaa, 0x2a, 0xab, 0x2c, 0x42, 0x41, 0x63, 0x13, 0x36, 0x01, 0x28,
	0x03, 0x6a, 0x91, 0x15, 0x8b, 0x14, 0x87, 0x32, 0x13, 0x11, 0x80, 0x00, 0x28, 0x89, 0x7f, 0x22,
	0x1f, 0x94, 0x2f, 0xc8, 0xeb, 0x7b, 0xb2, 0xca, 0x22, 0x35, 0x83, 0xc1, 0x63, 0x60, 0x49, 0xf1,
	0x0e, 0x7d, 0xfa, 0x9c, 0xe9, 0xd1, 0xe9, 0xee, 0x11, 0xa1, 0x77, 0x95, 0x9e, 0xc4, 0x49, 0x94,
	0x45, 0xa8, 0x15, 0xaf, 0xac, 0x2d, 0x74, 0xec, 0x60, 0x4a, 0x97, 0x6b, 0xf4, 0x0c, 0x34, 0x37,
	0xbd, 0x76, 0xce, 0x4d, 0xe5, 0x48, 0x19, 0x0d, 0xc7, 0xfa, 0x49, 0xbc, 0x3a, 0xb1, 0x03, 0x0e,
	0x91, 0x3c, 0x83, 0x4c, 0xe8, 0x9e, 0x45, 0xeb, 0xb7, 0x33, 0x1a, 0x9a, 0xad, 0x23, 0x65, 0xa4,
	0x91, 0x22, 0x44, 0x16, 0xec, 0x39, 0xa9, 0x1d, 0xed, 0xe2, 0x84, 0xa6, 0x29, 0x5d, 0x9b, 0xea,
	0x91, 0x32, 0xea, 0x11, 0x09, 0xb3, 0x7e, 0x6d, 0x41, 0xdf, 0x0e, 0x08, 0xbd, 0x65, 0x22, 0x64,
	0x80, 0x1a, 0xd0, 0x5b, 0x5e, 0x4c, 0x25, 0xec, 0x13, 0x7d, 0x0a, 0xda, 0x2c, 0xba, 0xde, 0xe6,
	0x67, 0xeb, 0xe3, 0x61, 0x7e, 0x01, 0x42, 0x6f, 0x39, 0x4a, 0xf2, 0x24, 0xfa, 0x12, 0xfa, 0x53,
	0xba, 0x4c, 0xb2, 0x15, 0x5d, 0x66, 0xbc, 0x8c, 0x3e, 0x46, 0x25, 0xb3, 0xcc, 0x90, 0x8a, 0x84,
	0xbe, 0x02, 0x3d, 0xa0, 0xd9, 0x65, 0x4a, 0x93, 0x70, 0xb9, 0xa3, 0x66, 0x9b, 0x6b, 0x0e, 0x4b,
	0x4d, 0x2d, 0x47, 0xea, 0x44, 0xf4, 0x05, 0xf4, 0x48, 0x14, 0xed, 0xec, 0x37, 0xcb, 0xcc, 0xd4,
	0xb8, 0xe8, 0xa0, 0x14, 0x15, 0x09, 0x52, 0x52, 0x0a, 0xfa, 0x6c, 0x9b, 0x66, 0x66, 0xe7, 0x1e,
	0x3a, 0x4b, 0x90, 0x92, 0xc2, 0xe8, 0xaf, 0xa2, 0x6d, 0xc8, 0x62, 0xb3, 0xdb, 0xa0, 0x17, 0x09,
	0x52, 0x52, 0xac, 0x7f, 0x72, 0xf3, 0xd2, 0xf8, 0x01, 0xf3, 0x46, 0xd0, 0xc5, 0x49, 0x62, 0x47,
	0x6b, 0xca, 0xed, 0x1b, 0xe6, 0xf6, 0x61, 0x42, 0x7c, 0xb2, 0xb0, 0xfd, 0x73, 0x4c, 0x8a, 0x34,
	0x7a, 0x0a, 0x1d, 0x9c, 0x24, 0x6e, 0x7a, 0xcd, 0xdd, 0xeb, 0x13, 0x11, 0x55, 0xf6, 0xb7, 0x25,
	0xfb, 0xd3, 0xf8, 0x61, 0xfb, 0x35, 0xc9, 0xfe, 0x34, 0x7e, 0x1f, 0xfb, 0x3b, 0x92, 0xfd, 0x69,
	0xfc, 0x5e, 0xf6, 0xcb, 0x06, 0xa5, 0xf1, 0x7f, 0xd8, 0xdf, 0xbb, 0x87, 0xfe, 0x88, 0xfd, 0xfd,
	0x06, 0xfd, 0x1e, 0xfb, 0x7f, 0xe1, 0xf6, 0x7b, 0xd9, 0x86, 0xdb, 0xff, 0x0c, 0xda, 0xaf, 0xb7,
	0x57, 0x3f, 0x70, 0xff, 0xf5, 0xf1, 0x20, 0x17, 0x7a, 0xd9, 0x86, 0x81, 0x84, 0xa7, 0x10, 0x06,
	0x83, 0x09, 0x5d, 0xba, 0x5b, 0xd1, 0xc4, 0x0f, 0x6f, 0xb6, 0x21, 0x15, 0x73, 0xfd, 0x61, 0x49,
	0x6f, 0x12, 0xc8, 0x3b, 0x12, 0xc9, 0x04, 0xb5, 0x7e, 0x4d, 0x21, 0x6f, 0x98, 0x70, 0x0a, 0xc0,
	0xbf, 0x6f, 0x22, 0xb6, 0x84, 0x79, 0x23, 0xff, 0x27, 0x0b, 0x78, 0x8a, 0xd4, 0x68, 0x4c, 0x34,
	0xdd, 0xa6, 0x59, 0x94, 0xbc, 0x65, 0x43, 0xa1, 0x35, 0x44, 0x55, 0x8a, 0xd4, 0x68, 0xd6, 0x08,
	0xa0, 0xda, 0x4d, 0xf4, 0x11, 0xf4, 0xca, 0x06, 0x2b, 0x7c, 0xaa, 0xca, 0xd8, 0xfa, 0x86, 0x33,
	0xc5, 0x18, 0xb1, 0xe9, 0x63, 0xa5, 0xc5, 0x33, 0xa3, 0x12, 0x11, 0x49, 0x27, 0xb4, 0x1a, 0x27,
	0x18, 0x30, 0x94, 0xb7, 0x5b, 0x20, 0xb5, 0x81, 0xb3, 0x4e, 0xc0, 0x68, 0x6e, 0xf3, 0xa3, 0xb7,
	0x42, 0x9c, 0x2f, 0x8d, 0x9f, 0xf5, 0x1c, 0x06, 0xd2, 0x72, 0xb3, 0xf7, 0xee, 0x2a, 0x0a, 0x33,
	0x1a, 0x66, 0x42, 0x5f, 0x84, 0xd6, 0x3e, 0xa7, 0x56, 0x83, 0x68, 0x9d, 0xd6, 0xb4, 0x7c, 0xc0,
	0x2c, 0xd8, 0x73, 0x97, 0x3f, 0xf3, 0x7c, 0x74, 0x27, 0x0e, 0xd0, 0x88, 0x84, 0x59, 0x3f, 0xe6,
	0xdd, 0x75, 0xc2, 0x4d, 0x84, 0x8e, 0xc1, 0xb0, 0xef, 0x92, 0x84, 0x86, 0x59, 0x3e, 0x00, 0xde,
	0xdd, 0x4e, 0x68, 0xde, 0xc1, 0xd1, 0xe7, 0x30, 0x9c, 0x47, 0xd9, 0xf2, 0xa6, 0x62, 0xe6, 0xcf,
	0x71, 0x03, 0xad, 0x99, 0xad, 0xd6, 0xcd, 0x16, 0x97, 0xad, 0xf6, 0x02, 0x59, 0xa0, 0xb1, 0xef,
	0xd4, 0x54, 0x8e, 0xd4, 0x91, 0x3e, 0xde, 0x63, 0xdd, 0x2f, 0x6e, 0x46, 0xf2, 0x94, 0x85, 0xc5,
	0x5f, 0x58, 0xec, 0xc4, 0x83, 0xad, 0xfc, 0x04, 0xfa, 0x76, 0x42, 0x97, 0x19, 0xf5, 0xe8, 0x4f,
	0xfc, 0x62, 0x3d, 0x52, 0x01, 0xa5, 0x73, 0xe5, 0x6a, 0xe9, 0x62, 0xb3, 0xd8, 0xda, 0x58, 0x1f,
	0xc0, 0xff, 0xef, 0x5d, 0x8d, 0xbc, 0x7a, 0x6d, 0xe8, 0x1f, 0x6b, 0x2e, 0xeb, 0x9b, 0x2d, 0xfa,
	0x96, 0xcf, 0x52, 0x11, 0x5a, 0x07, 0xb0, 0xdf, 0x58, 0x05, 0xeb, 0x35, 0xe8, 0x62, 0xae, 0xf9,
	0xb9, 0x08, 0xda, 0x9b, 0x24, 0xda, 0x89, 0x33, 0xf9, 0x37, 0x1a, 0x42, 0x6b, 0x5d, 0x1c, 0xd5,
	0x5a, 0x4b, 0x73, 0xa1, 0xca, 0x73, 0xf1, 0xb5, 0x38, 0xbf, 0xda, 0x14, 0xf4, 0x1c, 0xba, 0x22,
	0x12, 0xee, 0xee, 0x33, 0x77, 0x6b, 0x25, 0x49, 0x91, 0x3f, 0xfe, 0x0c, 0xa0, 0x7a, 0xb1, 0x91,
	0x0e, 0xdd, 0xe0, 0xd2, 0xb6, 0x71, 0x10, 0x18, 0x4f, 0x10, 0x40, 0xe7, 0xc5, 0xc4, 0x99, 0xe1,
	0x73, 0x43, 0x39, 0xfe, 0xbb, 0x05, 0x5d, 0xf1, 0x9f, 0x19, 0x0d, 0xa0, 0x4f, 0xf0, 0xb7, 0x8b,
	0x33, 0xfc, 0xd2, 0xf1, 0x8c, 0x27, 0x45, 0x38, 0xf3, 0x59, 0xa8, 0xa0, 0x03, 0x18, 0xb0, 0x70,
	0x8a, 0x27, 0x64, 0x7e, 0x86, 0x27, 0x73, 0xa3, 0x85, 0x0e, 0xc1, 0x60, 0x50, 0x80, 0xe7, 0x8b,
	0xcb, 0x00, 0x13, 0x6f, 0xe2, 0x62, 0x43, 0x2d, 0x88, 0xc4, 0xf7, 0xdd, 0x85, 0x3d, 0x9d, 0xcc,
	0x8d, 0xb6, 0x04, 0xcd, 0x9c, 0x60, 0x6e, 0x68, 0x05, 0xf4, 0xca, 0x77, 0x3c, 0x8e, 0x1b, 0x1d,
	0x5e, 0x30, 0xb8, 0x10, 0xf5, 0xd7, 0x45, 0x98, 0xd7, 0xa7, 0x5c, 0x10, 0x5c, 0xd4, 0xea, 0x6f,
	0x78, 0xfd, 0xe0, 0x42, 0xae, 0x7f, 0x5d, 0x10, 0xab, 0xfa, 0x6f, 0x24, 0x88, 0xd7, 0xdf, 0x16,
	0x50, 0x55, 0xff, 0x7b, 0x34, 0x84, 0xbe, 0x37, 0x7f, 0x21, 0xea, 0xff, 0xa6, 0xa0, 0x8f, 0xe1,
	0x29, 0x8b, 0xb9, 0xca, 0xc5, 0xee, 0x19, 0x26, 0x0b, 0xdf, 0x9b, 0x39, 0x1e, 0x36, 0x7e, 0x57,
	0x10, 0x82, 0x41, 0x99, 0xe4, 0x55, 0xfe, 0x50, 0xd0, 0x21, 0xec, 0x57, 0xd8, 0xcc, 0x0f, 0xf0,
	0xb9, 0xf1, 0x67, 0x89, 0x4e, 0x9d, 0x60, 0x4e, 0xfc, 0xef, 0x16, 0x6e, 0xf0, 0xd2, 0xf8, 0x4b,
	0x59, 0x75, 0xf8, 0xef, 0xa6, 0xd3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x3e, 0x1d, 0x61,
	0x43, 0x09, 0x00, 0x00,
}
